### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by paramat** [Ezhh/handholds#1]
Instead of the handholds node having handholds on all 4 sides how about it being 'facedir' rotatable and placed and rotated into the correct rotation when the tool is used, code being in the tool 'on use' code?
Erm maybe i'll try to dev this myself a bit, see where i get.

When removed it's rotation would define which direction climbable air is removed from.

**Comment by paramat** [comment]
I think i can solve your problem too, i'll try to code it.

**Comment by Ezhh** [comment]
@paramat Thank you.  I'm already planning to make it one side only, just didn't get time yet. Please let me attempt that part first (this is a good learning exercise).

For the issue we spoke about, ideas are very welcome.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L1689
The handholds node should be 'facedir' as a chest is, i think that will rotate it automatically. 
The handholds texture needs to be on the 'front' which is the 6th tile.

**Comment by paramat** [comment]
```
	--remove any climbable air nodes!
	on_destruct = function(pos
		local node = minetest.get_node(pos)
		local dir = minetest.facedir_to_dir(node.param2)
		local airpos = vector.add(pos, dir)

	end,
```
This is what i have so far, hopefullly airpos will be the air node adjacent to the handholds (but needs checking).

**Comment by paramat** [comment]
Then, before removing the air node, do a 'find node near' search, radius 1,  for handhold nodes, and don't remove if they are present.

**Comment by paramat** [comment]
For the 'on use' function:
'pointed_thing.above' will be the air node next to the face being pointed at, we can subtract 'pointed_thing.above' from 'pointed_thing.under' (or the other way around) to get a vector that can then be converted to a param2 rotation for placing the handholds node.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L40
'dir' is the vector.

**Comment by paramat** [comment]
```
	--remove any climbable air nodes!
	on_destruct = function(pos
		local node = minetest.get_node(pos)
		local dir = minetest.facedir_to_dir(node.param2)
		local airpos = vector.subtract(pos, dir)

	end,
```
^ That may have to be:
`local airpos = vector.subtract(pos, dir)`

**Comment by paramat** [comment]
Just realised, the 'find node near' search looks at diagonal neighbours too, so the air node will not be removed due to the handhold nodes above and below the one removed, this search needs to only look at surrounding nodes that are level with the air node. It will have to be 4 'get_nodes' instead.

**Comment by Ezhh** [comment]
Update: Placement (including node rotation) should now work correctly.
To do: Improvements for on_destruct.

**Comment by Ezhh** [comment]
on_destruct now only removes one node. 

Original problem (easily solvable) remains: up to four handholds nodes could be linked to one climbable air node, so on_destruct needs to check four positions. But sub-problem here is if climbable_air is buildable_to, we need people able to place nodes while there are other handholds and would also have unclimbable handholds again if placed nodes were later removed. 

@paramat Should I remove buildable_to because of this?

**Comment by paramat** [comment]
Hm what happens if you remove buildable_to then try to build a node where the climb air is, against one of the handhold nodes? The climb air is not pointable so i don't know what would happen.

**Comment by Ezhh** [comment]
It simply won't allow you to place a node there, whereas with buildable_to, attempting to place a node there would do so and remove climbable_air.

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/blob/master/mods/fire/init.lua#L84
Some sound code you could add at line 50 after the protection check, use 'pointed_thing.under' for the sound pos.

**Comment by paramat** [comment]
I'm unsure about buildable_to, perhaps best iti s not replaceable to avoid the frustration of having to place a new stone node (which are only craftable thorugh cooking) and chisel it again. Having a handholds node there but no climb air would confuse too.

**Comment by paramat** [comment]
Now this needs to work with desert stone and sandstone too, you'll need 3 handhold nodes.

The handholds texture could be a semi-transparent shading texture like my footprint texture https://github.com/minetest/minetest_game/blob/master/mods/default/textures/default_footprint.png that way it can be applied as an overlay to any texture and work. Or, you could make 3 different dedicated textures.
It will look more like holes in the stone if the upper part is shaded darker than the lower.

**Comment by paramat** [comment]
I suggest making the tool craftable from steel, to be generous.

**Comment by Ezhh** [comment]
Will remove buildable_to.

I don't play with sound myself, but I assume there is already a 'mining stone' sound which could be used here as well?

I definitely want to add handholds for the other kinds of stone.

And texture definitely needs some work. I was hoping to just use one texture for multiple nodes when finished, so I like the semi-transparent idea too.

**Comment by paramat** [comment]
Yes, https://github.com/minetest/minetest_game/blob/master/mods/default/sounds/default_dig_cracky.ogg that's played when digging stone.

**Comment by paramat** [comment]
When you support desert stone and sandstone, you could create a 'handholds' group for those, then in 'after destruct' you would check that group for the 4 surrounding nodes.
'if minetest.get_item_group(node.name, "handholds") == 0 then'

**Comment by Ezhh** [comment]
Removing nodes now works correctly - only one node is checked for climbable_air and rotation of surrounding nodes is considered.

**Comment by paramat** [comment]
Great, feel free to ask in this issue for any advice.

**Comment by Ezhh** [comment]
Added sound for tool use and changed tool recipe to use steel ingots.

To do: Improve textures, create handholds group, and enable handholds for desert stone and sandstone.

**Comment by Ezhh** [comment]
Everything listed here should now be included. Closing this, but please let me know if you have further ideas.
