### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by Billre** [Ezhh/handholds#3]
Increase base durability and perhaps make it a set of tools with increasing durabilities.

**Comment by paramat** [comment]
Tool breaks when wear reaches 2^16, so uses = 2^16 / wear-per-use.
Since this is only used to cut small holes in each node think the uses can be very high, we could think in terms of depth reachable with 1 tool, y = -1024? That would be add_wear(64).

**Comment by Ezhh** [comment]
Thanks paramat. Tool durability adjusted, so will close this now. :)
