### ISSUE TITLE
Add cobblestone and desert cobblestone to the list

### ISSUE THREAD

**Issue by Fixer-007** [Ezhh/handholds#4]
There is a lot of structures and places with cobblestones, it might be useful to also add them to the list (since  a lot of sneak ladders were out of cobblestone since I remember it).

**Comment by paramat** [comment]
The handholds texture will not look good overlayed on cobble.
I suggested keeping this to just the 4 natural terrain nodes used in mapgen since this is mainly for long vertical journeys underground or on mountains.

**Comment by Ezhh** [comment]
I'm inclined to agree with paramat on this. The handholds won't work well with 'busier' textures like the cobble ones, and I feel they should be reserved for naturally occurring nodes. Also, even though this mod can help with the sneak ladder issue, it's not a direct replacement, and sneak ladders often using cobble isn't a good reason to have handholds work with cobble.

Fixer, if you want a version of this for your own use that does work with cobble, I'd be happy to make that for you separately, but as it stands I won't add cobble to the main version of the mod here.
