### ISSUE TITLE
Check for buildable = true before placing climb air?

### ISSUE THREAD

**Issue by paramat** [Ezhh/handholds#5]
Otherwise climb air can replace slabs, stairs or any partial node.
Climb air will also create air bubbles underwater but i think that's a minor concern probably not worth checking for.

**Comment by Ezhh** [comment]
I considered the air bubbles previously in a discussion with Billre, but normal ladders also have this issue. Until there is a way to address replacing air with water for all underwater nodes, I think that will remain (and so is an issue outside of this mod).

Interesting issue for partial nodes, but I think buildable = true is not the correct approach. We'd need to instead prevent the handhold itself from being placed, or  it opens a situation where you can then remove the partial node and have unclimbable handholds.

**Comment by paramat** [comment]
Yes that's what i mean, check for buildable before placing handholds or climb air.

**Comment by paramat** [comment]
It could be included in the big conditional at line 119.

**Comment by paramat** [comment]
A check for protection at pointed_thing.above might be good there too.

**Comment by Ezhh** [comment]
Sorry, I should have been more clear. I meant check for buildable when placing air is not the right approach, but rather check for it where the air will go when placing the handholds instead.  I'll probably make the change tomorrow, as I'm not really fully awake. :)

**Comment by Ezhh** [comment]
Will look into protection check too.

**Comment by Ezhh** [comment]
Protection check fixed.

**Comment by Ezhh** [comment]
And added buildable to check. Would appreciate if you could take a look. I'll close the issue if you agree I've done this correctly.
